export interface LegalSection {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
}

export interface LegalPageContent {
  path: string;
  eyebrow: string;
  title: string;
  summary: string;
  metaTitle: string;
  metaDescription: string;
  lastUpdated: string;
  sections: LegalSection[];
}

const lastUpdated = "27 July 2026";

export const legalPages: LegalPageContent[] = [
  {
    path: "/privacy",
    eyebrow: "Privacy",
    title: "Privacy Policy",
    summary:
      "This policy explains how QRF Limited collects, uses, stores and protects personal information received through this website and our business enquiries.",
    metaTitle: "Privacy Policy | QRF Papua New Guinea",
    metaDescription:
      "Read how QRF Limited handles personal information submitted through the QRF website and business enquiry channels.",
    lastUpdated,
    sections: [
      {
        id: "scope",
        title: "1. Who this policy applies to",
        paragraphs: [
          "This Privacy Policy applies to visitors to qrfpng.com and people who contact QRF Limited through the website, email, telephone or another business enquiry channel. In this policy, “QRF”, “we”, “our” and “us” refer to QRF Limited.",
          "The policy covers personal information handled for website enquiries, consultation requests, project discussions, supplier or partner communications and support-related contact.",
        ],
      },
      {
        id: "information-we-collect",
        title: "2. Information we may collect",
        paragraphs: [
          "We collect information that you choose to provide and limited technical information that may be generated when you use the website.",
        ],
        bullets: [
          "Your name, organisation, email address and telephone number.",
          "Your preferred contact method, location, solution interests and the details of your requirement.",
          "Correspondence, enquiry history and information needed to prepare or manage a response.",
          "Basic technical records such as IP address, browser type, device information, requested pages, timestamps and security logs where generated by our hosting or security providers.",
        ],
      },
      {
        id: "how-we-use-information",
        title: "3. How we use personal information",
        paragraphs: [
          "We use personal information only where it is reasonably necessary for QRF’s business activities, to respond to a request, to protect the website or where required by law.",
        ],
        bullets: [
          "Assessing and responding to enquiries, consultation requests and support needs.",
          "Communicating about relevant QRF solutions, quotations, site assessments and project delivery.",
          "Maintaining business records and improving our services and website.",
          "Detecting spam, misuse, security incidents or other harmful activity.",
          "Meeting legal, regulatory, accounting or contractual obligations.",
        ],
      },
      {
        id: "cookies",
        title: "4. Cookies and website technology",
        paragraphs: [
          "The website may use essential browser storage or similar technology needed for navigation, security, accessibility and reliable operation. Hosting infrastructure may also create routine server logs.",
          "QRF does not use information submitted through the enquiry form to build advertising profiles. If non-essential analytics or marketing technology is introduced, this policy and any required visitor controls should be updated before that technology is enabled.",
        ],
      },
      {
        id: "sharing",
        title: "5. When information may be shared",
        paragraphs: [
          "QRF does not sell personal information. We may share information with personnel, contractors and service providers who need it to perform work for QRF, including website hosting, communications, professional advice, security and enquiry-management services.",
          "Information may also be disclosed where required by law, to protect a person or QRF’s lawful interests, or as part of a business reorganisation. We take reasonable steps to limit disclosures to what is necessary.",
        ],
      },
      {
        id: "security-retention",
        title: "6. Security and retention",
        paragraphs: [
          "We use reasonable administrative and technical safeguards appropriate to the nature of the information. No internet transmission or storage system is completely secure, so visitors should not submit passwords, access codes, private keys or other sensitive credentials through the enquiry form.",
          "We keep personal information only for as long as it is reasonably needed for the purpose for which it was collected, for business records, dispute management and applicable legal obligations. Information that is no longer required is deleted, de-identified or securely disposed of where practical.",
        ],
      },
      {
        id: "access-correction",
        title: "7. Access, correction and contact preferences",
        paragraphs: [
          "You may ask us to confirm whether we hold personal information about you, request access to it, ask for inaccurate information to be corrected, or ask us to stop non-essential communications. We may need to verify your identity and may retain information where the law or a legitimate business requirement permits it.",
          "To make a request, email info@qrfpng.com and describe the information or communication concerned.",
        ],
      },
      {
        id: "third-party-links",
        title: "8. Third-party websites",
        paragraphs: [
          "This website may link to manufacturers, technology providers or other third parties. Their websites and privacy practices are controlled by those organisations. Review their privacy notices before providing information to them.",
        ],
      },
      {
        id: "changes",
        title: "9. Changes to this policy",
        paragraphs: [
          "We may update this policy when our website, services or legal obligations change. The current version will be published on this page with its effective date.",
        ],
      },
    ],
  },
  {
    path: "/terms",
    eyebrow: "Website terms",
    title: "Terms of Use",
    summary:
      "These terms govern access to and use of the QRF website. By continuing to use the website, you agree to these terms.",
    metaTitle: "Terms of Use | QRF Papua New Guinea",
    metaDescription:
      "Terms governing access to and use of the QRF Limited website, content, enquiry tools and linked resources.",
    lastUpdated,
    sections: [
      {
        id: "acceptance",
        title: "1. Acceptance of these terms",
        paragraphs: [
          "These Terms of Use apply to qrfpng.com and its content and enquiry features. The website is operated by QRF Limited. If you do not agree with these terms, please do not use the website.",
          "Additional written terms may apply to quotations, projects, products, support arrangements or other services supplied by QRF. Those specific terms take priority for the relevant transaction if they conflict with these website terms.",
        ],
      },
      {
        id: "website-purpose",
        title: "2. Website purpose",
        paragraphs: [
          "The website provides general information about QRF, its capabilities and the types of solutions it may be able to supply. Website content is not a binding offer, technical design, service commitment, warranty or quotation.",
          "A solution’s suitability, availability, specifications, coverage, lead time and price must be confirmed through a written assessment or quotation from QRF.",
        ],
      },
      {
        id: "permitted-use",
        title: "3. Permitted use",
        paragraphs: [
          "You may view, download or print reasonable extracts from the website for legitimate personal or internal business evaluation. You must preserve any copyright, trade mark and attribution notices.",
        ],
        bullets: [
          "Do not interfere with the website, its hosting, security controls or other users.",
          "Do not attempt unauthorised access, vulnerability testing, automated extraction or malicious code delivery.",
          "Do not use the website or its content for unlawful, misleading, fraudulent or infringing activity.",
          "Do not reproduce, republish or commercially exploit substantial website content without QRF’s written permission.",
        ],
      },
      {
        id: "intellectual-property",
        title: "4. Intellectual property",
        paragraphs: [
          "Unless otherwise stated, QRF or its licensors own the website design, text, graphics, photographs and other original content. QRF grants only the limited permission described in these terms.",
          "Product names, logos and trade marks belonging to manufacturers or other third parties remain the property of their respective owners. Their appearance does not transfer ownership or create rights beyond any separately confirmed commercial relationship.",
        ],
      },
      {
        id: "enquiries",
        title: "5. Enquiries and communications",
        paragraphs: [
          "You are responsible for ensuring information submitted through the website is accurate, lawful and appropriate to share. Do not submit passwords, network credentials, access codes, classified material or sensitive operational data through the general enquiry form.",
          "Submitting an enquiry does not create a customer, supplier, partnership, agency or advisory relationship. A commercial relationship begins only when the parties agree to appropriate written terms.",
        ],
      },
      {
        id: "availability",
        title: "6. Availability and changes",
        paragraphs: [
          "We may change, suspend or withdraw website content or features without notice. We aim to keep the website useful and available, but do not guarantee uninterrupted, error-free or secure access.",
        ],
      },
      {
        id: "third-parties",
        title: "7. Third-party content and links",
        paragraphs: [
          "Links to third-party websites are provided for convenience or product context. QRF does not control those websites and is not responsible for their availability, accuracy, security, content or terms.",
        ],
      },
      {
        id: "liability",
        title: "8. Responsibility and liability",
        paragraphs: [
          "To the extent permitted by law, QRF excludes warranties implied solely from access to this website and is not liable for loss arising from reliance on general website content, temporary unavailability, third-party material or unauthorised interference with the website.",
          "Nothing in these terms excludes a right or liability that cannot lawfully be excluded or limited.",
        ],
      },
      {
        id: "governing-law",
        title: "9. Governing law",
        paragraphs: [
          "These website terms are governed by the laws of Papua New Guinea. Courts with jurisdiction in Papua New Guinea will have jurisdiction over disputes concerning these terms, subject to any mandatory legal right or agreed dispute process.",
        ],
      },
      {
        id: "changes",
        title: "10. Changes and contact",
        paragraphs: [
          "We may update these terms by publishing a revised version on this page. Questions about these terms can be sent to info@qrfpng.com.",
        ],
      },
    ],
  },
  {
    path: "/disclaimer",
    eyebrow: "Important information",
    title: "Website Disclaimer",
    summary:
      "This disclaimer explains the limits of general website information and why operational solutions require a site-specific assessment.",
    metaTitle: "Website Disclaimer | QRF Papua New Guinea",
    metaDescription:
      "Important limitations applying to general information, imagery, product references and technical material on the QRF website.",
    lastUpdated,
    sections: [
      {
        id: "general-information",
        title: "1. General information only",
        paragraphs: [
          "Content on this website is provided as a general introduction to QRF and the solution categories we work with. It is not legal, financial, safety, engineering, cybersecurity or other professional advice and should not be relied on as a substitute for an assessment by appropriately qualified personnel.",
        ],
      },
      {
        id: "technical-decisions",
        title: "2. Technical and operational decisions",
        paragraphs: [
          "Communications, internet, satellite, radio, CCTV, security and network outcomes depend on factors including site conditions, terrain, coverage, power, existing infrastructure, licensing, configuration, environmental exposure, third-party networks and user requirements.",
          "Do not purchase equipment, alter a system, make a safety decision or plan business continuity solely from website content. QRF should confirm the design, assumptions and scope for the specific environment.",
        ],
      },
      {
        id: "accuracy",
        title: "3. Accuracy and currency",
        paragraphs: [
          "QRF takes reasonable care when preparing website content but does not guarantee that every item is complete, current or free from error. Specifications, vendor offerings, coverage, availability, pricing and regulatory requirements may change.",
        ],
      },
      {
        id: "images",
        title: "4. Images and visual representations",
        paragraphs: [
          "Images on this website may be illustrative, composited or representative of a solution in operation. They may not depict an actual QRF customer site, completed project, exact product configuration or current stock item unless expressly identified as such.",
          "Network lines, signals, interface graphics and similar visual effects are explanatory design elements and are not coverage maps, performance measurements or engineering diagrams.",
        ],
      },
      {
        id: "brands",
        title: "5. Third-party products and brands",
        paragraphs: [
          "Third-party product names, trade marks and images belong to their respective owners. References are used to identify technologies or solution categories and do not, by themselves, imply endorsement, exclusivity, certification or a particular partnership status.",
          "Any authorised reseller, installer or partner status should be confirmed against QRF’s current written documentation and the relevant vendor’s requirements.",
        ],
      },
      {
        id: "external-links",
        title: "6. External links",
        paragraphs: [
          "QRF is not responsible for information, downloads, security or availability on third-party websites. A link does not mean QRF approves all content or practices of the linked organisation.",
        ],
      },
      {
        id: "security",
        title: "7. Security and internet risks",
        paragraphs: [
          "No website, email transmission or internet-connected system can be guaranteed completely secure. Visitors are responsible for using appropriate device, browser and network protections and for avoiding the submission of credentials or highly sensitive information through general website channels.",
        ],
      },
      {
        id: "liability",
        title: "8. Limitation",
        paragraphs: [
          "To the extent permitted by law, QRF is not responsible for loss arising from reliance on general website content, inability to access the website, third-party content or decisions made without a project-specific assessment. Nothing in this disclaimer limits a right or obligation that cannot lawfully be limited.",
        ],
      },
      {
        id: "contact",
        title: "9. Confirm information with QRF",
        paragraphs: [
          "For current product information, a site assessment, a written quotation or confirmation of QRF’s capabilities and commercial relationships, contact the QRF team at info@qrfpng.com.",
        ],
      },
    ],
  },
];

